#!/bin/bash
# =============================================================================
# gen_machine_list.sh -- regenerate machine_list.txt from /etc/hosts
# =============================================================================
# On CloudLab the experiment LAN is described in /etc/hosts (10.10.1.0/24 here),
# so that file is the single source of truth for which workers exist. Node names
# change with every experiment instantiation, hence this regenerator rather than
# a hand-maintained list.
#
# Two things this handles that a naive `cut` would not:
#   * The CONTROL node (this host) is excluded -- it runs the job server and is
#     not a worker. Registering it would let the server schedule jobs onto
#     itself.
#   * Output uses "user@host" form. setup_all_machines.sh / add_all_machines.sh
#     parse with `awk '$i ~ /@|\./'`, which only picks fields containing '@' or
#     '.'; a bare "node1" has neither and would be SILENTLY DROPPED, leaving an
#     empty fleet.
#
# Usage:  scripts/gen_machine_list.sh [-n]
#   -n   dry run: print to stdout, do not write the file
#
# Env overrides:
#   MACHINE_LIST           output file      (default machine_list.txt)
#   EXPJOBSERVER_SSH_USER  ssh user         (default $(whoami))
#   LAN_PREFIX             host LAN prefix  (default 10.10.1.)
#   CONTROL_NODE           node to exclude  (default $(hostname -s))
# =============================================================================
set -euo pipefail

cd "$(dirname "$0")/.." || exit 1

MACHINE_LIST="${MACHINE_LIST:-machine_list.txt}"
SSH_USER="${EXPJOBSERVER_SSH_USER:-$(whoami)}"
LAN_PREFIX="${LAN_PREFIX:-10.10.1.}"
CONTROL_NODE="${CONTROL_NODE:-$(hostname -s)}"

DRY_RUN=false
[[ "${1:-}" == "-n" ]] && DRY_RUN=true

# Match hosts on the experiment LAN; take each line's LAST field, which is the
# bare short name (/etc/hosts lists "10.10.1.2  node1-link-1 node1-0 node1").
generate() {
    printf '%s\n' \
        "# machine_list.txt -- generated by scripts/gen_machine_list.sh on $(date '+%Y-%m-%d %H:%M:%S')" \
        "# Source of truth: /etc/hosts (experiment LAN ${LAN_PREFIX}0/24)." \
        "# Control node ($CONTROL_NODE) is excluded: it runs the server, it is not a worker." \
        "# 'user@host' form is required -- the list parser only picks fields containing" \
        "# '@' or '.', so a bare 'node1' would be silently dropped."
    awk -v ctl="$CONTROL_NODE" -v user="$SSH_USER" -v pfx="$LAN_PREFIX" '
        index($1, pfx) == 1 {
            short = $NF
            if (short != ctl) print user "@" short
        }' /etc/hosts | sort -V
}

out="$(generate)"

# Guard against writing an empty fleet (wrong LAN_PREFIX, unexpected /etc/hosts).
if ! grep -qv '^#' <<<"$out"; then
    echo "[ERROR] No workers found on ${LAN_PREFIX}0/24 in /etc/hosts (control: $CONTROL_NODE)." >&2
    echo "        Check LAN_PREFIX / CONTROL_NODE." >&2
    exit 1
fi

if [[ "$DRY_RUN" == "true" ]]; then
    printf '%s\n' "$out"
else
    printf '%s\n' "$out" > "$MACHINE_LIST"
    echo "[INFO] Wrote $(grep -cv '^#' <<<"$out") worker(s) to $MACHINE_LIST"
    grep -v '^#' <<<"$out" | sed 's/^/       /'
fi
